service: cosmos-alerting
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  send:
    handler: src/handler.sendMsg
    events:
      - http:
          path: /send
          method: post
          cors: true

plugins:
  - serverless-offline
